Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Aprendendo sobre as variáveis
// Autor(a)    : João Vitor Vivas Faria da Silva
// Data atual  : 10/03/2022
Var
// Seção de Declarações das variáveis 
// primeiro nome
// segundo nome
// idade
// cidade
// endereço

   primeiroNome, segundoNome, cidade, endereco: caractere
   idade: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo